### ISSUE TITLE
Adding a line

### ISSUE THREAD

**Issue by ahijevyc** [ccht-ncsu/Kalpana#13]
In addition to filled contours, I would like to add a storm track.  Would that be a useful and appropriate addition to this software?

**Comment by ahijevyc** [comment]
Something on the lines of FigureGen, where it reads a text file with lon lat pairs.

**Comment by rosemaryc** [comment]
Hello David,

That is a great suggestion and will definitely make kalpana more useful. Thank you very much for your efforts to correct bugs and improve the source code. We appreciate your contributions!

- Rosemary

**Comment by ahijevyc** [comment]
Glad to hear - I will work on that.  Thanks for making  this package available.
