### ISSUE TITLE
Missing maximum variable in filledcontour function when extracting time series data from netcdf 

### ISSUE THREAD

**Issue by tmiesse** [ccht-ncsu/Kalpana#64]
When using nc2shp function with a polygon variable for time series adcirc output it will trip at this line. Needs to be adjusted so that it includes a max value variable that is commonly referenced at other uses of this function as "orgMaxLevel"
https://github.com/ccht-ncsu/Kalpana/blob/613d63e1bc2e34fa5ffa4e9ae8f4e54be0d65fbc/kalpana/export.py#L501

**Comment by tomas19** [comment]
Thanks for pointing that out. I'll try to find time to fix it

**Comment by tmiesse** [comment]
No worries. Happy to help.

**Comment by tomas19** [comment]
Problem solved, thanks again!
