### ISSUE TITLE
Upload Test Data for Downscaling

### ISSUE THREAD

**Issue by msw17002** [ccht-ncsu/Kalpana#90]
Hello,

This isn't an issue.

If possible, could you please upload a test dataset for downscaling? 

This link no longer works: https://drive.google.com/drive/folders/1cbQzN4SrLs_rVlz9q8zHCKbFtQpLO5CG?usp=sharing

I'd like to ensure the stability of my conda environment.

**Comment by tomas19** [comment]
Hi sorry for my late reply.

Try the files in the link below. That is the link from the readme in the examples folder in the repo. Downscaling section point 3.
Please let me know how it goes.

https://drive.google.com/drive/folders/14gOAzbfuMUk3asRFsMCtOup3NL3V6EgF

Tomas
