### ISSUE TITLE
downscaling without the fort.14 file?

### ISSUE THREAD

**Issue by glw** [ccht-ncsu/Kalpana#92]
Hi @tomas19 Its not clear to me If you do not have the fort.14 file and only the maxele netcdf file. Can you still downscale? I see most of the examples in the repo use the fort.14 file. Thanks!

**Comment by glw** [comment]
Just following up on the above @tomas19 . Thank you.

**Comment by tomas19** [comment]
Hi, yes it is possible to run the downscaling without having the fort.14. The mesh information is also contained in the netCDF files
